Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

AllCops:
  TargetRubyVersion: 2.4

FrozenStringLiteralComment:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Documentation:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
